FROM docker.io/node:18.7.0 as builder

RUN apt update && \
    apt upgrade -y

WORKDIR /app
COPY . .

RUN make install && \
    make proto -B

RUN npm i
RUN npm run build

######## Start a new stage from scratch #######
FROM docker.io/nginx:1.23.1-alpine

COPY --from=builder /app/dist /etc/static
COPY --from=builder /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf