FROM docker.io/node:19.2.0 as builder

RUN apt update && \
    apt upgrade -y

# jq is a tool that makes it easy to edit the contents of a JSON file from the CLI.
RUN wget --no-check-certificate https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 -O /tmp/jq-linux64
RUN cp /tmp/jq-linux64 /usr/bin/jq
RUN chmod +x /usr/bin/jq

WORKDIR /app
COPY . .

# overwrites config.json to convert it into a dictionary of environment variable keys
RUN jq 'to_entries | map_values({ (.key) : ("$" + .key) }) | reduce .[] as $item ({}; . + $item)' ./src/config.json > ./src/config.tmp.json && mv ./src/config.tmp.json ./src/config.json

RUN make install && \
    make proto -B

RUN npm i
RUN npm run build

######## Start a new stage from scratch #######
FROM docker.io/nginx:1.23.2-alpine

COPY --from=builder /app/dist /etc/static
COPY --from=builder /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf

COPY scripts/start-nginx.sh /usr/bin/start-nginx.sh
RUN chmod +x /usr/bin/start-nginx.sh

ENTRYPOINT [ "start-nginx.sh" ]