FROM docker.io/node:19.2.0 as builder

RUN apt update && \
    apt upgrade -y

# for more details about dynamic environment variables look at:
# https://developers.redhat.com/blog/2021/03/04/making-environment-variables-accessible-in-front-end-containers#inject_the_environment_variables
ENV JQ_VERSION=1.6
RUN wget --no-check-certificate https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-linux64 -O /tmp/jq-linux64
RUN cp /tmp/jq-linux64 /usr/bin/jq
RUN chmod +x /usr/bin/jq

WORKDIR /app
COPY . .

RUN jq 'to_entries | map_values({ (.key) : ("$" + .key) }) | reduce .[] as $item ({}; . + $item)' ./src/config.json > ./src/config.tmp.json && mv ./src/config.tmp.json ./src/config.json

RUN make install && \
    make proto -B

RUN npm i
RUN npm run build

######## Start a new stage from scratch #######
FROM docker.io/nginx:1.23.2-alpine

COPY --from=builder /app/dist /etc/static
COPY --from=builder /app/nginx/nginx.conf /etc/nginx/conf.d/default.conf

ENV JSFOLDER=/etc/static/js/*.js
COPY scripts/start-nginx.sh /usr/bin/start-nginx.sh
RUN chmod +x /usr/bin/start-nginx.sh

ENTRYPOINT [ "start-nginx.sh" ]