/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.14.0
 * source: user.proto
 * git: https://github.com/thesayyn/protoc-gen-ts
 *  */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace user {
    export class SignupRequest extends pb_1.Message {
        constructor(data?: any[] | {
            email?: string;
            pwd?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("email" in data && data.email != undefined) {
                    this.email = data.email;
                }
                if ("pwd" in data && data.pwd != undefined) {
                    this.pwd = data.pwd;
                }
            }
        }
        get email() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set email(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get pwd() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set pwd(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            email?: string;
            pwd?: string;
        }) {
            const message = new SignupRequest({});
            if (data.email != null) {
                message.email = data.email;
            }
            if (data.pwd != null) {
                message.pwd = data.pwd;
            }
            return message;
        }
        toObject() {
            const data: {
                email?: string;
                pwd?: string;
            } = {};
            if (this.email != null) {
                data.email = this.email;
            }
            if (this.pwd != null) {
                data.pwd = this.pwd;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.email === "string" && this.email.length)
                writer.writeString(1, this.email);
            if (typeof this.pwd === "string" && this.pwd.length)
                writer.writeString(2, this.pwd);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SignupRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SignupRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.email = reader.readString();
                        break;
                    case 2:
                        message.pwd = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SignupRequest {
            return SignupRequest.deserialize(bytes);
        }
    }
    export class DeleteRequest extends pb_1.Message {
        constructor(data?: any[] | {
            pwd?: string;
            totp?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("pwd" in data && data.pwd != undefined) {
                    this.pwd = data.pwd;
                }
                if ("totp" in data && data.totp != undefined) {
                    this.totp = data.totp;
                }
            }
        }
        get pwd() {
            return pb_1.Message.getField(this, 1) as string;
        }
        set pwd(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get totp() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set totp(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            pwd?: string;
            totp?: string;
        }) {
            const message = new DeleteRequest({});
            if (data.pwd != null) {
                message.pwd = data.pwd;
            }
            if (data.totp != null) {
                message.totp = data.totp;
            }
            return message;
        }
        toObject() {
            const data: {
                pwd?: string;
                totp?: string;
            } = {};
            if (this.pwd != null) {
                data.pwd = this.pwd;
            }
            if (this.totp != null) {
                data.totp = this.totp;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (typeof this.pwd === "string" && this.pwd.length)
                writer.writeString(1, this.pwd);
            if (typeof this.totp === "string" && this.totp.length)
                writer.writeString(2, this.totp);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): DeleteRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new DeleteRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.pwd = reader.readString();
                        break;
                    case 2:
                        message.totp = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): DeleteRequest {
            return DeleteRequest.deserialize(bytes);
        }
    }
    export class TotpRequest extends pb_1.Message {
        constructor(data?: any[] | {
            action?: TotpRequest.actions;
            pwd?: string;
            totp?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("action" in data && data.action != undefined) {
                    this.action = data.action;
                }
                if ("pwd" in data && data.pwd != undefined) {
                    this.pwd = data.pwd;
                }
                if ("totp" in data && data.totp != undefined) {
                    this.totp = data.totp;
                }
            }
        }
        get action() {
            return pb_1.Message.getField(this, 1) as TotpRequest.actions;
        }
        set action(value: TotpRequest.actions) {
            pb_1.Message.setField(this, 1, value);
        }
        get pwd() {
            return pb_1.Message.getField(this, 2) as string;
        }
        set pwd(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get totp() {
            return pb_1.Message.getField(this, 3) as string;
        }
        set totp(value: string) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            action?: TotpRequest.actions;
            pwd?: string;
            totp?: string;
        }) {
            const message = new TotpRequest({});
            if (data.action != null) {
                message.action = data.action;
            }
            if (data.pwd != null) {
                message.pwd = data.pwd;
            }
            if (data.totp != null) {
                message.totp = data.totp;
            }
            return message;
        }
        toObject() {
            const data: {
                action?: TotpRequest.actions;
                pwd?: string;
                totp?: string;
            } = {};
            if (this.action != null) {
                data.action = this.action;
            }
            if (this.pwd != null) {
                data.pwd = this.pwd;
            }
            if (this.totp != null) {
                data.totp = this.totp;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.action !== undefined)
                writer.writeEnum(1, this.action);
            if (typeof this.pwd === "string" && this.pwd.length)
                writer.writeString(2, this.pwd);
            if (typeof this.totp === "string" && this.totp.length)
                writer.writeString(3, this.totp);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TotpRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TotpRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.action = reader.readEnum();
                        break;
                    case 2:
                        message.pwd = reader.readString();
                        break;
                    case 3:
                        message.totp = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TotpRequest {
            return TotpRequest.deserialize(bytes);
        }
    }
    export namespace TotpRequest {
        export enum actions {
            ENABLE = 0,
            DISABLE = 1
        }
    }
    export class Empty extends pb_1.Message {
        constructor(data?: any[] | {}) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], []);
            if (!Array.isArray(data) && typeof data == "object") { }
        }
        static fromObject(data: {}) {
            const message = new Empty({});
            return message;
        }
        toObject() {
            const data: {} = {};
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Empty {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Empty();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Empty {
            return Empty.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedUserServiceService {
        static definition = {
            Signup: {
                path: "/user.UserService/Signup",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SignupRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SignupRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Empty.deserialize(new Uint8Array(bytes))
            },
            Delete: {
                path: "/user.UserService/Delete",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: DeleteRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => DeleteRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Empty.deserialize(new Uint8Array(bytes))
            },
            Totp: {
                path: "/user.UserService/Totp",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: TotpRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => TotpRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: Empty) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => Empty.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract Signup(call: grpc_1.ServerUnaryCall<SignupRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract Delete(call: grpc_1.ServerUnaryCall<DeleteRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
        abstract Totp(call: grpc_1.ServerUnaryCall<TotpRequest, Empty>, callback: grpc_1.sendUnaryData<Empty>): void;
    }
    export class UserServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedUserServiceService.definition, "UserService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options)
        }
        Signup: GrpcUnaryServiceInterface<SignupRequest, Empty> = (message: SignupRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Empty>, callback?: grpc_1.requestCallback<Empty>): grpc_1.ClientUnaryCall => {
            return super.Signup(message, metadata, options, callback);
        };
        Delete: GrpcUnaryServiceInterface<DeleteRequest, Empty> = (message: DeleteRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Empty>, callback?: grpc_1.requestCallback<Empty>): grpc_1.ClientUnaryCall => {
            return super.Delete(message, metadata, options, callback);
        };
        Totp: GrpcUnaryServiceInterface<TotpRequest, Empty> = (message: TotpRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<Empty>, options?: grpc_1.CallOptions | grpc_1.requestCallback<Empty>, callback?: grpc_1.requestCallback<Empty>): grpc_1.ClientUnaryCall => {
            return super.Totp(message, metadata, options, callback);
        };
    }
}
